# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5777382b042e369a9e7f4697217d42fada470cb0512261ceb722ea0de1b1f465e0876af48fd2403b17399dfd8bc72b9f2e0b8bfcedb7bdb2809c29a1873c5169

test:
  secret_key_base: 55a64ffd8f702161358d5103d39649cf18ee9b66d98454f1c72b489bddd8d0f836d14c2f82bc3e6b0025bbc87d2035f8b074932b28507102a698968db02044e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
